### ISSUE TITLE
expected an intended block?

### ISSUE THREAD

**Issue by Windywind** [lifanxi/rpimenu#1]
![qq 20150501212256](https://cloud.githubusercontent.com/assets/9924858/7430773/04f4e60e-f04a-11e4-9d31-0c7dc4cf6ba8.jpg)
Like the pic shows, I don' know why this error.
Any help?

**Comment by lifanxi** [comment]
You need to indent your code block for the **init** function. 

Python uses indent instead of {} (compare to C or Java) to identify code blocks.

**Comment by Windywind** [comment]
But I didn't modify the codes, why would this happen? BTW, if I have to intend, which block should I intend?

**Comment by Windywind** [comment]
@lifanxi

**Comment by lifanxi** [comment]
Sorry, I haven't noticed that you have changed the file name, so I didn't realize that the indention problem is in Adafruit_CharLCD.py.

It is strange that why I haven't noticed that these files has indention problems before, these code runs well 2 years ago on my Raspberry Pi. 

I have fixed the problems, please get the latest version and test again. I will try to figure out why I didn't notice the problem before later. 

Thank you for reporting the problem.
